title: John Wooten
description: "Decentralizing Capitlism ğŸŒ"
url: "jfwooten4.com"
github_username:  JFWooten4
theme: minima
plugins:
  - jekyll-feed
include:
  - imgs
  - _headers
exclude:
  - site # Excludes Docusaurus site from the Jekyll build
defaults:
  - scope:
      path: "sticky-notes" # Many sticky-notes contain `{{ ... }}` which Liquid will try to interpret.
    values:
      render_with_liquid: false # Treat them as literal text while still letting Jekyll render Markdown.
